FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

WORKDIR /app

COPY docker/requirements_baseline.txt .
RUN pip install --no-cache-dir -r requirements_baseline.txt

COPY server_baseline_gpu.py .
COPY model.py .

EXPOSE 8000

CMD ["python", "server_baseline_gpu.py"]